name: New Feature
description: Comprehensive description of improvement proposition
title: "[Feature name]"
labels: ["feature"]

body:
  - type: markdown
    attributes:
        value: |
          Thank for contributing your improvement propositions!
  - type: textarea
    id: Description
    attributes:
      label: "Desciprtion"
      description: "What is the feature? What does the feature enable to do? May include: precondition, flow, postcondition"
    validations:
      required: true
