name: New Feature
description: Comprehensive description of improvement proposition
title: "[Feature]: "
labels: ["feature"]

body:
  - type: markdown
    attributes:
        value: |
          Thanks for taking the time to fill out this bug report!
  - type: input
    id: Description
    attributes:
      label: Feature description. May include: precondition, flow, postcondition
      description: "What is the feature? What does the feature enable to do?"
      placeholder: Dark mode
    validations:
      required: true
